name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
        default: 'auto'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run version bump script
        id: bump
        run: |
          source .venv/bin/activate

          # Run bump script with dry-run to get new version
          OUTPUT=$(python scripts/bump_version.py --type ${{ inputs.bump_type }} --dry-run)
          echo "$OUTPUT"

          # Extract new version
          NEW_VERSION=$(echo "$OUTPUT" | grep "New version:" | awk '{print $3}')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Run actual bump (without tag)
          python scripts/bump_version.py --type ${{ inputs.bump_type }} --no-tag

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): bump version to ${{ steps.bump.outputs.new_version }}"

      - name: Push to dev
        run: |
          git push origin dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/v${{ steps.bump.outputs.new_version }}
          base: main
          title: "Release v${{ steps.bump.outputs.new_version }}"
          body: |
            ## Release v${{ steps.bump.outputs.new_version }}

            This PR prepares the release of version ${{ steps.bump.outputs.new_version }}.

            ### Changes

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ### Checklist

            - [ ] All tests pass
            - [ ] Documentation is updated
            - [ ] CHANGELOG.md is updated
            - [ ] Version numbers are bumped

            ### After Merge

            1. A GitHub release will be automatically created
            2. Distribution packages will be built
            3. Tag `v${{ steps.bump.outputs.new_version }}` will be created

            ---

            🤖 This PR was automatically created by the release workflow.
          labels: |
            release
            automated
